Repository wecode-bootcamp-korea/43-2nd-comebackhome-frontend, pull requests merged in 2023-04, with the labels that each got.

#17 [43기 문은빈]ADD: 집들이리스트 기능구현(상품 필터링, 데이터받아오기)
  src/config.js
  src/pages/HomepartyList/HomepartyList.js
  src/pages/HomepartyList/HomepartyListStyled.js
Labels: 완료

#16 [43기 신정호] order UI 구현
  public/data/Order.json
  public/data/productDetail.json
  src/components/OrderProduct/OrderProduct.js
  src/components/OrderProduct/OrderProductStyle.js
  src/pages/Order/Order.js
  src/pages/Order/OrderStyle.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 완료

#18 [43기 문은빈] 메인페이지 기능 구현(캐러셀 분할, 하단 쇼핑리스트 8개 제한 노출 )
  public/data/HomeParty.json
  public/data/ProductItem.json
  public/images/slide/pic/pic1.png
  public/images/slide/pic/pic2.png
  public/images/slide/pic/pic3.png
  public/images/slide/slide1.jpg
  public/images/slide/slide2.jpg
  public/images/slide/slide3.jpg
  public/images/slide/slide5.jpg
  public/images/slide/slide6.jpg
  src/Router.js
  src/components/Cart/GroupCart/GroupCart.js
  src/components/Cart/GroupCart/GroupCartStyle.js
  src/components/Nav/Nav.js
  src/components/Nav/NavStyle.js
  src/components/Product/Product.js
  src/components/Product/ProductStyled.js
  src/pages/Cart/CartStyle.js
  src/pages/HomepartyDetail/HomepartyDetail.js
  src/pages/HomepartyDetail/HomepartyDetailStyled.js
  src/pages/HomepartyList/HomepartyListStyled.js
  src/pages/Main/Main.js
  src/pages/Main/MainStyled.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailStyle.js
  src/pages/ProductList/ProductList.js
  src/pages/ShoppingList/ShoppingList.js
  src/pages/Signin/SignInStyle.js
  src/styles/GlobalStyle.js
  src/styles/common.js
Labels: 완료

#21 [43기 문은빈] 집들이 상세페이지 기능 구현
  package-lock.json
  package.json
  public/data/CommentCopy.json
  public/data/DetailItem.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Product/Product.js
  src/config.js
  src/pages/HomepartyDetail/Component/Comment.js
  src/pages/HomepartyDetail/Component/CommentStyled.js
  src/pages/HomepartyDetail/Component/ReComment.js
  src/pages/HomepartyDetail/Component/ReCommentStyled.js
  src/pages/HomepartyDetail/HomepartyDetail.js
  src/pages/HomepartyDetail/HomepartyDetailStyled.js
  src/pages/HomepartyList/HomepartyList.js
  src/pages/Main/Main.js
  src/pages/ProductList/Component/Component.js
  src/pages/ProductList/ProductList.js
  src/pages/Signin/Redirect.js
Labels: 완료

#19 [43기 이기태 ] 장바구니 페이지 기능구현(체크박스, 상품삭제, 결제금액, 수량변경)
  public/data/CartData.json
  src/components/Cart/CartCount/CartCount.js
  src/components/Cart/CartCount/CartCountStyle.js
  src/components/Cart/EmptyCart/EmptyCartStyle.js
  src/components/Cart/GroupCart/CartCheckbox/CartCheckbox.js
  src/components/Cart/GroupCart/CartCheckbox/CartCheckboxStyle.js
  src/components/Cart/GroupCart/CheckboxInput/CheckboxInput.js
  src/components/Cart/GroupCart/CheckboxInput/CheckboxInputStyle.js
  src/components/Cart/GroupCart/GroupCart.js
  src/components/Cart/GroupCart/OrderdList.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartStyle.js
Labels: 수정 요청

#20 [43기 문은빈]ADD: 페이지네이션 기능 구현
  public/data/ProductItem.json
  src/components/Nav/Nav.js
  src/config.js
  src/pages/HomepartyDetail/Component/Comment.js
  src/pages/HomepartyDetail/HomepartyDetail.js
  src/pages/HomepartyDetail/HomepartyDetailStyled.js
  src/pages/Main/Main.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductListStyle.js
  src/pages/Signin/Redirect.js
Labels: 완료

#23 [43기 이기태 문은빈 신정호] 최종본
  public/data/CartData.json
  public/data/CommentCopy.json
  public/data/DetailItem.json
  public/data/HomeParty.json
  public/data/HomepartyList.json
  public/data/ItemData.json
  public/data/Order.json
  public/data/ProductItem.json
  public/data/productDetail.json
  public/images/30평 거실.jpg
  public/images/HomepartyList/1-9평 화장실.jpg
  public/images/HomepartyList/10평 방.jpg
  public/images/HomepartyList/10평대 주방.jpg
  public/images/HomepartyList/20평 거실.jpg
  public/images/HomepartyList/20평 홈오피스.jpg
  public/images/HomepartyList/30평 거실.jpg
  public/images/HomepartyList/user.jpg
  public/images/dinnertable.png
  public/images/pic.jpg
  public/images/shoppingItem/item1.jpg
  public/images/shoppingItem/item2.jpeg
  public/images/slide/slide1.jpg
  public/images/slide/slide2.jpg
  public/images/slide/slide3.jpg
  public/images/slide/slide4.jpg
  public/images/slide/slide5.jpg
  public/images/slide/slide6.jpg
  src/assets/images/메인23.png
  src/assets/images/상세 페이지.png
  src/components/Cart/CartCount/CartCountStyle.js
  src/components/Cart/EmptyCart/EmptyCart.js
  src/components/Cart/GroupCart/GroupCart.js
  src/components/Cart/GroupCart/GroupCartStyle.js
  src/components/Footer/Footer.js
  src/components/GlobalModal/GlobalModal.js
  src/components/GlobalModal/OrderModal.js
  src/components/Nav/Nav.js
  src/components/OrderProduct/OrderProduct.js
  src/components/Product/Product.js
  src/config.js
  src/pages/HomepartyDetail/Component/Comment.js
  src/pages/HomepartyDetail/HomepartyDetail.js
  src/pages/Order/Order.js
  src/pages/Order/OrderStyle.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/Signin/Redirect.js
  src/styles/common.js
Labels: 멘토 리뷰 요청
